baseURL = 'https://prthkms.com/'

# theme = 'coder'
# theme = 'hugo-bearcub'
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Pratheek Mahishi"
author = "Pratheek Mahishi"
copyright = "Copyright © 2023, Pratheek Mahishi."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"


[markup.highlight]
style = "github-light"

[params]
  description = "Pratheek Mahishi's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "img/profile-pic1.png"

  faviconSVG = "img/favicon.svg"
  favicon_32 = "img/favicon-p-32.png"
  favicon_16 = "img/favicon-p-16.png"

  enableTwemoji = true
  title = "Pratheek Mahishi"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/prthkms/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/prthkms/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

# [[menu.main]]
#  name = "About"
#  weight = 2
#  url = "about/"