baseURL = 'https://prthkms.com/'

# theme = 'coder'
# theme = 'hugo-bearcub'
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Pratheek Mahishi"
author = "Pratheek Mahishi"
copyright = "Copyright © 2023, Pratheek Mahishi."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"


[params]
  description = "Pratheek Mahishi's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "img/profile-pic1.png"

  favicon = "img/favicon.svg"

  enableTwemoji = true
  title = "Pratheek Mahishi"

